apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oci-block-volume-n8n-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Tamanho do PVC que ser√° requisitado
  storageClassName: oci-bv